name: Move new issues into Triage
permissions: write-all
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "test1"
          column: "lmao"
          repo-token: ${{ secrets.LMAO }}
